sets:
- prefix: ios
  icons:
  # iOS
  - width: 57
    height: 57
    type: rounded
    radius: 9
  - width: 72
    height: 72
    type: rounded
    radius: 11
  - width: 114
    height: 114
    type: rounded
    radius: 18
  - width: 144
    height: 144
    type: rounded
    radius: 23
  - width: 512
    height: 512
    type: rounded
    radius: 80
  - width: 1024
    height: 1024
    type: rounded
    radius: 180
- prefix: android
  icons:
  # Android
  - width: 36
    height: 36
    type: circle
  - width: 48
    height: 48
    type: circle
  - width: 72
    height: 72
    type: circle
  - width: 96
    height: 96
    type: circle
  - width: 144
    height: 144
    type: circle
  - width: 192
    height: 192
    type: circle
- prefix: diamond
  icons:
  - width: 200
    height: 200
    type: diamond
  - width: 120
    height: 120
    type: diamond
  - width: 380
    height: 380
    type: diamond
